package def.primeng.primeng;
import def.angular.core.ElementRef;
import def.angular.core.EventEmitter;
import def.angular.core.IterableDiffers;
import jsweet.lang.Function;
public class Schedule extends jsweet.lang.Object {
    public ElementRef el;
    public Object[] events;
    public Object header;
    public Object style;
    public String styleClass;
    public Boolean rtl;
    public Boolean weekends;
    public double[] hiddenDays;
    public Boolean fixedWeekCount;
    public Boolean weekNumbers;
    public Object businessHours;
    public Object height;
    public Object contentHeight;
    public double aspectRatio;
    public Object eventLimit;
    public Object defaultDate;
    public Boolean editable;
    public Boolean eventStartEditable;
    public Boolean eventDurationEditable;
    public String defaultView;
    public Boolean allDaySlot;
    public String allDayText;
    public Object slotDuration;
    public Object slotLabelInterval;
    public Object snapDuration;
    public Object scrollTime;
    public Object minTime;
    public Object maxTime;
    public Boolean slotEventOverlap;
    public Boolean nowIndicator;
    public double dragRevertDuration;
    public double dragOpacity;
    public Boolean dragScroll;
    public Object eventOverlap;
    public Object eventConstraint;
    public Object locale;
    public Function eventRender;
    public EventEmitter<?> onDayClick;
    public EventEmitter<?> onEventClick;
    public EventEmitter<?> onEventMouseover;
    public EventEmitter<?> onEventMouseout;
    public EventEmitter<?> onEventDragStart;
    public EventEmitter<?> onEventDragStop;
    public EventEmitter<?> onEventDrop;
    public EventEmitter<?> onEventResizeStart;
    public EventEmitter<?> onEventResizeStop;
    public EventEmitter<?> onEventResize;
    public EventEmitter<?> viewRender;
    public Boolean initialized;
    public Boolean stopNgOnChangesPropagation;
    public Object differ;
    public Object schedule;
    public Schedule(ElementRef el, IterableDiffers differs){}
    native public void ngAfterViewInit();
    native public void ngDoCheck();
    native public void ngOnDestroy();
    native public void gotoDate(Object date);
    native public void prev();
    native public void next();
    native public void prevYear();
    native public void nextYear();
    native public void today();
    native public void incrementDate(Object duration);
    native public Object getDate();
    protected Schedule(){}
}

